version: '3'
services:
  piwik:
    image: udata/piwik-test
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
   image: mysql
   environment:
     MYSQL_ROOT_PASSWORD: piwik
     MYSQL_DATABASE: piwik
     MYSQL_USER: piwik
     MYSQL_PASSWORD: piwik
